<?php

return [

    'hear_about' => [
        'linkedin' => 'LinkedIn',
        'creator' => 'Another creator',
        'word_of_mouth' => 'Word of mouth',
        'google' => 'Google search',
        'other' => 'Other',
    ],

    'industries' => [
        'B2B',
        'B2C',
        'AI',
        'SaaS',
        'Software',
        'Sales',
        'Marketing',
        'SEO',
        'Outreach',
        'CRM',
        'Creative',
        'Productivity',
        'Fintech',
        'HealthTech',
        'EdTech',
        'Cybersecurity',
        'Growth / GTM',
        'HR',
        'E-commerce',
        'Developer Tools',
        'Data / Analytics',
        'Customer Support',
        'Design',
        'Real Estate / PropTech',
        'LegalTech',
        'InsurTech',
        'Logistics / Supply Chain',
        'Recruiting / Talent',
        'Web3 / Crypto',
        'Agencies / Consulting',
        'Media / Content',
        'Retail',
        'Manufacturing',
        'Hospitality / Travel',
        'Energy / CleanTech',
    ],

    'countries' => [
        'AT' => 'Austria',
        'AU' => 'Australia',
        'BE' => 'Belgium',
        'BR' => 'Brazil',
        'CA' => 'Canada',
        'CH' => 'Switzerland',
        'CZ' => 'Czechia',
        'DE' => 'Germany',
        'DK' => 'Denmark',
        'ES' => 'Spain',
        'FI' => 'Finland',
        'FR' => 'France',
        'GB' => 'United Kingdom',
        'IE' => 'Ireland',
        'IN' => 'India',
        'IT' => 'Italy',
        'NL' => 'Netherlands',
        'NO' => 'Norway',
        'PL' => 'Poland',
        'PK' => 'Pakistan',
        'PT' => 'Portugal',
        'SE' => 'Sweden',
        'SG' => 'Singapore',
        'US' => 'United States',
        'AE' => 'United Arab Emirates',
        'OTHER' => 'Other',
    ],

];
